//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaTechAndSolve.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTrips
    {
        public int Id { get; set; }
        public Nullable<int> Document { get; set; }
        public Nullable<System.DateTime> DateProcess { get; set; }
        public string UrlFileProcess { get; set; }
    }
}
